steps:
  - name: ":beer:"
    command: "make clean-machine"
  - name: ":baby:"
    command: "make machine"
  - name: ":allthethings:"
    command: "make hello"
  - name: ":notes:"
    command: "make compose"
  - name: ":whale:"
    command: "docker-machine ls && docker images && docker ps -a"
  - name: ":metal"
    command: 'echo "$(docker-machine ip test) api.xxx.com" | sudo tee --append /etc/hosts'
  - name: ":sleeping:"
    command: "sleep 9999999999"
    
  # - name: ":packer:"
  #   command: "packer build"
